from typing import TypedDict, List


class QuoteItem(TypedDict):
    """Schema for a quote line item."""
    product_name: str
    product_code: str
    quantity: int
    unit_price: float
    currency: str
    incoterm: str  # FOB, CIF
    lead_time_days: int


class QuoteResult(TypedDict, total=False):
    """Schema for generated quote."""
    quote_id: str
    customer_email: str
    items: List[QuoteItem]
    total_amount: float
    valid_until: str
    shipping_port: str
    payment_terms: str
    notes: str


QUOTE_GENERATION_PROMPT = """
You are a pharmaceutical pricing expert generating a formal quote.

Based on the following context, generate a detailed quote in JSON format:

【Retrieved Similar Emails】
{similar_emails}

【Customer History】
{customer_history}

【Applicable Pricing Policy】
{pricing_policy}

【Compliance Requirements】
{compliance}

【Original Inquiry】
{original_email}

Output a JSON object with this exact schema:
{{
  "quote_id": "<auto-generated UUID>",
  "customer_email": "<customer email>",
  "items": [
    {{
      "product_name": "<product name>",
      "product_code": "<product code if known>",
      "quantity": <number>,
      "unit_price": <price per unit in USD>,
      "currency": "USD",
      "incoterm": "FOB|CIF",
      "lead_time_days": <days to delivery>
    }}
  ],
  "total_amount": <total USD amount>,
  "valid_until": "<quote expiration date, YYYY-MM-DD>",
  "shipping_port": "<departure port>",
  "payment_terms": "<payment terms>",
  "notes": "<any additional notes>"
}}

Pricing guidelines:
1. Use the pricing_policy to determine base prices
2. Apply customer tier discounts from customer_history
3. For Brazil: add ANVISA compliance costs
4. For large orders (>10000 units): apply volume discount
5. Standard payment terms: 30% advance, 70% against B/L

Output ONLY the JSON, no additional text.
"""
